services:
  web:
    image: git.vichingo455.com/emmev-code/orario:latest
    container_name: orario-web
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: unless-stopped
    environment:
      DB_HOST: db # Host database
      DB_USER: orario # Utente database
      DB_PASS: orario # Password dell'utente del database
      DB_NAME: school_timetable # Nome del database
  db:
    image: mariadb:12
    container_name: orario-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd # Password dell'utente root del database
      MYSQL_DATABASE: school_timetable # Nome del database, da impostare in DB_NAME
      MYSQL_USER: orario # Utente del database, da impostare in DB_USER
      MYSQL_PASSWORD: orario # Password del database, da impostare in DB_PASS
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
  db_data: